paulscherrerinstitute/scilog

sci-log-db/src/application.ts

should close: #34 
when no JWT_SECRET env variable is provided, a random one is generated. 
This fixes the potential security issue of loopback setting the jwt_secret = myjwts3cr3t when none is specified. This results in any jwt token signed with such a secret (even created outside of the app) being suitable to be authorised

Add option to provide jwt secret at app startime

---

sci-log-db/src/__tests__/acceptance/basesnippet.controller.acceptance.ts
sci-log-db/src/mixins/basesnippet.repository-mixin.ts

Job repo in addition with default ACLs computation result in circular dependency.
This is because:
- when calling the basesnippets/export endpoint, a basesnippet repo is created
- the export method creates a job by injecting the job repo
- if the exported content has a parentId, the job creation tries to create the job default ACLs
- the defaultACLs tries to find the snippet with the parent of the created job, and for that it calls the basenippet repo
So this results in basesnippetRepo -> jobrepo -> basesnippetRepo
Using the create of basesnippet setting explicitely the snippetType avoids the circular dependency

Avoid injecting job repo

---

config/be/roles.js
docker-compose.dev.yaml
sci-log-db/src/__tests__/unit/authentication-strategies.roles.unit.ts
sci-log-db/src/authentication-strategies/roles.ts
sci-log-db/src/authentication-strategies/types.ts

even if this seems quite PSI specific, it's possible to provide any roles mapping by bind mounting the roles.js file in the dist/authentication-strategies folder in the container, in pure JS. See the [docker-compose.dev.yaml backend container](https://github.com/paulscherrerinstitute/scilog/blob/bf605f312a69564eb13adf8ceef7de9e984b8d10/docker-compose.dev.yaml#L20).

Add eaccount mappings and its tests

---

sci-log-db/src/__tests__/unit/service.export-snippet.unit.ts
sci-log-db/src/services/export-snippets.service.ts

pdfLatex complains and fails to generate pdf when .tex file has nested \begin{verbatim} \end{verbatim} as it fails to resolve opening and closing blocks. This PR avoids adding outer {verbatim} blocks when multiple are nested

Fix nested latex verbatim failing

---

sci-log-db/src/__tests__/acceptance/basesnippet.controller.acceptance.ts
sci-log-db/src/mixins/basesnippet.repository-mixin.ts
sci-log-db/src/repositories/autoadd.repository.base.ts

Refactoring of /search to run query on db rather than parsing results. If {include: ['subsnippets']} is specified the search is performed on subsnippets as well, going in the direction of #64 . 
@wakonig , @stephan271 I have not removed the search bar when inside a logbook as to me it does not seem to have any particular issue. Please comment on that if you think otherwise.

Refactor search endpoint to leverage loobpack

---

sci-log-db/src/__tests__/acceptance/setupapp.acceptance.ts
sci-log-db/src/application.ts
sci-log-db/src/express-handlers/middleware-sequence.ts
sci-log-db/src/express-handlers/session-store.ts
sci-log-db/src/sequence.ts
sci-log-db/src/session-store.ts

It avoids instantiate sessions multiple times leading to login failures

Force middlewares as singleton

---

scilog/src/app/app.component.spec.ts
scilog/src/app/app.component.ts
scilog/src/app/logbook/logbook.component.spec.ts
scilog/src/app/logbook/logbook.component.ts

Injecting the logbook service into the appComponent caused the browser to do infinite redirects on login

Move logbook unsetting on back from app to logbook

---

sci-log-db/src/__tests__/unit/service.export-snippet.unit.ts
sci-log-db/src/services/export-snippets.service.ts

Add timestamp to exported snippets

---

scilog/src/app/core/model/edits.ts
scilog/src/app/core/remote-data.service.spec.ts
scilog/src/app/core/remote-data.service.ts
scilog/src/app/logbook/core/add-content/add-content.component.html
scilog/src/app/logbook/core/add-content/add-content.component.spec.ts
scilog/src/app/logbook/core/add-content/add-content.component.ts
scilog/src/app/logbook/core/snippet/snippet-content/snippet-content.component.spec.ts
scilog/src/app/logbook/core/snippet/snippet-content/snippet-content.component.ts
scilog/src/app/logbook/core/snippet/snippet.component.html
scilog/src/app/logbook/core/snippet/snippet.component.spec.ts
scilog/src/app/logbook/core/snippet/snippet.component.ts
scilog/src/app/logbook/widgets/logbook-item/logbook-item.component.spec.ts
scilog/src/app/logbook/widgets/logbook-item/logbook-item.component.ts

This only covers the websocket locking, the locking on loading the page is not yet implemented and will come in another PR, as it implements a newer feature

Change snippet locking basing it on edit snippets

---

scilog/src/app/logbook/core/snippet/snippet.component.html
scilog/src/app/logbook/core/snippet/snippet.component.spec.ts
scilog/src/app/logbook/core/snippet/snippet.component.ts
scilog/src/app/logbook/widgets/todos/todos.component.html
scilog/src/app/logbook/widgets/todos/todos.component.spec.ts
scilog/src/app/logbook/widgets/todos/todos.component.ts
scilog/src/app/overview/add-logbook/add-logbook.component.html
scilog/src/app/overview/add-logbook/add-logbook.component.spec.ts
scilog/src/app/overview/add-logbook/add-logbook.component.ts
scilog/src/app/overview/is-allowed.service.spec.ts
scilog/src/app/overview/is-allowed.service.ts
scilog/src/app/overview/logbook-cover/logbook-cover.component.html
scilog/src/app/overview/logbook-cover/logbook-cover.component.spec.ts
scilog/src/app/overview/logbook-cover/logbook-cover.component.ts

Introduces a services to select allowed actions and checks them for "snippets" and "todos" in addition to "cover" and "logbook edit"

Refactor allowed actions using service

---

scilog/src/app/overview/logbook-cover/logbook-cover.component.css

for some very obscure reason, in old browsers, doing in css
```
.a {
.b {}
}
```
is not the same as 
```
.a .b {}
```
do you maybe know why @wakonig

Firefox fitting

---

sci-log-db/src/__tests__/acceptance/basesnippet.controller.acceptance.ts
sci-log-db/src/__tests__/acceptance/file.controller.acceptance.ts
sci-log-db/src/__tests__/acceptance/location.controller.acceptance.ts
sci-log-db/src/__tests__/acceptance/logbook.controller.acceptance.ts
sci-log-db/src/__tests__/acceptance/paragraph.controller.acceptance.ts
sci-log-db/src/__tests__/acceptance/task.controller.acceptance.ts
sci-log-db/src/__tests__/unit/utils.misc.unit.ts
sci-log-db/src/mixins/basesnippet.repository-mixin.ts
sci-log-db/src/utils/misc.ts
scilog/src/app/logbook/core/search-window/search-window.component.spec.ts
scilog/src/app/logbook/core/search-window/search-window.component.ts

This refactor should allow searching leveraging mongo/lb capabilities and expand the search recursively to all subsnippets levels.
For convenience the search has special chars which encode `tag` and `users`

Refactor search recursively

---

sci-log-db/src/__tests__/unit/utils.misc.unit.ts
sci-log-db/src/utils/misc.ts

Given that the array is mutable and that its lenght is changed recursively, the index passed during recursion would not get the value consistently. For this reason the index is lookedup from the array using the snippet ID

Fix error when removing empty subsnippets

---

scilog/src/app/logbook/core/search-window/search-window.component.html
scilog/src/app/logbook/core/search-window/search-window.component.spec.ts
scilog/src/app/logbook/core/search-window/search-window.component.ts
scilog/src/app/overview/overview.component.css
scilog/src/app/overview/overview.component.html
scilog/src/app/overview/overview.component.spec.ts
scilog/src/app/overview/overview.component.ts

Submit search on enter

---

sci-log-db/src/__tests__/unit/service.export-snippet.unit.ts
sci-log-db/src/mixins/basesnippet.repository-mixin.ts
sci-log-db/src/services/export-snippets.service.ts

This is required as when editing paragraphs with attachments, the `href` is changed to the FE `download` route and the file reference is removed in the DB snippet. 
TODO: think about keeping the file reference.

Attachment after update

---

scilog/src/app/logbook/core/search-window/search-window.component.css
scilog/src/app/logbook/core/search-window/search-window.component.html
scilog/src/app/logbook/core/search-window/search-window.component.spec.ts
scilog/src/app/logbook/core/search-window/search-window.component.ts

Apply widget preferences to search

---

scilog/src/app/app.module.ts
scilog/src/app/core/remote-data.service.spec.ts
scilog/src/app/core/remote-data.service.ts
scilog/src/app/overview/overview-table/overview-table.component.html
scilog/src/app/overview/overview-table/overview-table.component.scss
scilog/src/app/overview/overview-table/overview-table.component.spec.ts
scilog/src/app/overview/overview-table/overview-table.component.ts
scilog/src/app/overview/overview.component.html
scilog/src/app/overview/overview.component.spec.ts
scilog/src/app/overview/overview.component.ts

Replaces overview headlines view with table view, with sorting, pagination and draggable columns

---

scilog/src/app/overview/overview-table/overview-table.component.html
scilog/src/app/overview/overview-table/overview-table.component.scss

* Extend scrolling to firefox
* Decrease rows height
* Decrease image size
* Fit whole viewport

Extend scrolling to firefox

---

README.md
config/docker-compose.yaml
config/fe/config.json
config/fe/simple_config.json

This prevents cors problems when using another url than localhost

Add traefik to compose

---

config/be/datasource.json
config/be/functionalAccounts.json
sci-log-db/src/__tests__/acceptance/functional-accounts.acceptance.ts
sci-log-db/src/__tests__/acceptance/test-helper.ts
sci-log-db/src/__tests__/testdb.datasource.ts
sci-log-db/src/application.ts
sci-log-db/src/observers/create-functional-accounts.observer.ts
sci-log-db/src/observers/no-unx-descendants-query.ts

As there is a logic that takes the unxGroup from functional accounts for a given location and adds it to all logbooks that are descendants of that location, this PR takes into account the case where a functional account with a location and a unxGroup is created after the logbooks referencing that location already exist. In this case it should propagate the unxGroups to the existing logbooks

Add unx group recursively based on FA

---

sci-log-db/src/__tests__/acceptance/user.controller.acceptance.ts
sci-log-db/src/controllers/user.controller.ts

The POST /users endpoint in SciLog is unauthenticated, hence, an attacker is able to create a user (functional account) with admin rights.
https://scilog.psi.ch/api/v1/explorer/#/UserController/UserController.create 
Logging in with the created functional account https://scilog.psi.ch/login (username: [scilog-admin@YOURDOMAIN](mailto:scilog-admin@YOURDOMAIN) and password: xxx). Able to view / delete all Logbooks
Added admin authorization to /users endpoint. Fixed and added corresponding tests

Require admin authorization for POST /users

---

scilog/.gitignore
scilog/package-lock.json
scilog/package.json
scilog/src/app/app-config.service.ts
scilog/src/app/app-routing.module.ts
scilog/src/app/app.module.ts
scilog/src/app/auth-callback/auth-callback.component.html
scilog/src/app/auth-callback/auth-callback.component.spec.ts
scilog/src/app/auth-callback/auth-callback.component.ts
scilog/src/app/core/auth-services/auth.interceptor.spec.ts
scilog/src/app/core/auth-services/auth.interceptor.ts
scilog/src/app/core/auth-services/auth.service.ts
scilog/src/app/core/config/server-settings.service.ts
scilog/src/app/core/dataset.service.spec.ts
scilog/src/app/core/dataset.service.ts
scilog/src/app/logbook/dashboard/dashboard-item/dashboard-item.component.html
scilog/src/app/logbook/widgets/scicat-viewer/scicat-viewer.component.css
scilog/src/app/logbook/widgets/scicat-viewer/scicat-viewer.component.html
scilog/src/app/logbook/widgets/scicat-viewer/scicat-viewer.component.spec.ts
scilog/src/app/logbook/widgets/scicat-viewer/scicat-viewer.component.ts
scilog/src/app/logbook/widgets/widget-preferences/widget-preferences.component.html
scilog/src/app/logbook/widgets/widget-preferences/widget-preferences.component.spec.ts
scilog/src/app/logbook/widgets/widget-preferences/widget-preferences.component.ts
scilog/src/app/login/login.component.html
scilog/src/assets/config-example.json

This PR implements a widget that displays a user-selected dataset from SciCat. An interceptor is implemented to detect a call to scicat backend, and if unauthorized, to fetch a scicat token for the OIDC user. 
We use support added in https://github.com/SciCatProject/scicat-backend-next/pull/1714 and pass `scilog` as `clientId` and the current path as `returnURL` to SciCat (to /auth/oidc/login). SciCat then returns the access token to `<scilog-frontend>/auth-callback` (configured as successURL for clientId scilog in SciCat i.e. `OIDC_SCILOG_SUCCESS_URL`) along with the passed returnUrl. The AuthCallback component in Scilog then stores the scicat token and routes the frontend to /returnUrl.
A first implementation of Dataset viewer is added, along with link to the corresponding dataset page …

SciCat Dataset widget

---

scilog/src/app/app.component.scss
scilog/src/app/core/toolbar/toolbar.component.html
scilog/src/app/core/toolbar/toolbar.component.ts
scilog/src/app/logbook/core/settings/settings.component.css
scilog/src/app/logbook/core/settings/view-settings/view-edit/view-edit.component.css
scilog/src/app/logbook/core/settings/view-settings/view-settings.component.css
scilog/src/styles.scss
scilog/src/styles/_global.scss

`::ng-deep` should not be used as it makes the style global and breaks Angular's [ViewEncapsulation](https://angular.dev/guide/components/styling#viewencapsulationemulated), making it hard to reason about which style will apply to a given component. 
This results in a bug that: if clicks on `User settings` on the toolbar first, then opens the Widget preference in a logbook, the padding gets overriden to 0 because the User settings component exported a global style with ng-deep.
Fixed this according to this [SO answer](https://stackoverflow.com/a/45933595/6459429).

Fix global style error for mat-dialog-container

---

scilog/src/app/core/auth-services/auth.interceptor.ts
scilog/src/app/core/config/server-settings.service.ts

Recently, the returnUrl query parameter name in `/v3/auth/oidc` endpoint was updated: https://github.com/SciCatProject/scicat-backend-next/pull/1815. Updating it here as well, to preserve the intended behavior (that the user lands on the opened logbook after authenticating with SciCat and not on overview page.)

(fix) update returnURL to returnUrl due to changed query parameter name in SciCat

---

sci-log-db/src/__tests__/acceptance/logbook.controller.acceptance.ts
sci-log-db/src/controllers/logbook.controller.ts
sci-log-db/src/models/logbook.model.ts
sci-log-db/src/repositories/autoadd.repository.base.ts
scilog/src/app/core/remote-data.service.ts
scilog/src/app/logbook/logbook.component.spec.ts
scilog/src/app/logbook/logbook.component.ts
scilog/src/app/overview/overview-table/overview-table.component.html
scilog/src/app/overview/overview-table/overview-table.component.spec.ts
scilog/src/app/overview/overview-table/overview-table.component.ts
scilog/src/app/overview/overview.component.ts

- Added an indexed `touchedAt` field to Logbook model
- Added an endpoint `PATCH /logbooks/{id}/touch` which updates the `touchedAt` to current time
- Added acceptance test for the endpoint
- Added a client method for the touch endpoint in LogbookDataService
- Calling the touch endpoint whenever the logbook page is visited
- Added an additional field `Last opened` in the overview-table
- Make default sort order `touchedAt DESC` rather than previous defaultOrder
Tested locally that the table filter works as expected, and in the overview scroll the last touched logbooks bubble to the top

(feat) ability to sort logbooks by last touched
