sci-log-db/src/__tests__/acceptance/setupapp.acceptance.ts
sci-log-db/src/__tests__/acceptance/test-helper.ts
sci-log-db/src/__tests__/testdb.datasource.ts
sci-log-db/src/application.ts
sci-log-db/src/index.ts
sci-log-db/src/observers/create-functional-accounts.observer.ts
sci-log-db/src/utils/websocket.ts

* Remove hardcoded values
* Add test for setting up datasource

Allow db config read from file,reuse on websocket

---

sdk/python/py_scilog/Dockerfile
sdk/python/py_scilog/docker-compose.yaml
sdk/python/py_scilog/poetry.lock
sdk/python/py_scilog/pyproject.toml
sdk/python/py_scilog/scilog/authmixin.py
sdk/python/py_scilog/scilog/httpclient.py
sdk/python/py_scilog/scilog/scicat.py
sdk/python/py_scilog/scilog/scilog.py
sdk/python/py_scilog/update_locations.py

* add Dockerfile
* add poetry files to keep track of dependencies
* add docker-compose for local dev
* generalise python code to take credentials from env

Enable scilog sdk to take credentials from env

---

scilog/Dockerfile
scilog/nginx.conf

Add nginx.conf to enable reload

Add dockerfile to build angular app

---

sci-log-db/docker-compose.test.yaml
sci-log-db/src/__tests__/acceptance/file.controller.acceptance.ts
sci-log-db/src/__tests__/acceptance/oidc.acceptance.ts
sci-log-db/src/__tests__/acceptance/test-helper.ts
sci-log-db/src/__tests__/testdb.datasource.ts
sci-log-db/src/controllers/file.controller.ts

@stephan271 I've got rid of the endpoint   `@patch('/filesnippet/{id}/files')` because it doesn't seem to be used. 
Plz let me know if I should add it back

Add tests for gridfs functionality, bind to mongo

---

scilog/src/app/overview/logbook-cover/logbook-cover.component.html

clicking the logbook icon now forwards to the corresponding dashboard

open logbook when icon is clicked; closes #32

---

sci-log-db/src/controllers/basesnippet.controller.ts
scilog/src/app/core/remote-data.service.ts
scilog/src/app/overview/logbook-icon-scroll-service.service.spec.ts
scilog/src/app/overview/logbook-icon-scroll-service.service.ts
scilog/src/app/overview/overview.component.css
scilog/src/app/overview/overview.component.html
scilog/src/app/overview/overview.component.ts

lazy loading for logbook overview

Lazy logbooks; closes #54

---

scilog/src/app/logbook/core/logbook-scroll.service.ts
scilog/src/app/logbook/core/scroll-base.service.ts

attempt to fix viewport jumping; closes #44

---

sci-log-db/src/__tests__/acceptance/basesnippet.controller.acceptance.ts
sci-log-db/src/mixins/basesnippet.repository-mixin.ts

Search on readacl

---

sci-log-db/src/__tests__/acceptance/file.controller.acceptance.ts
sci-log-db/src/__tests__/acceptance/location.controller.acceptance.ts
sci-log-db/src/__tests__/acceptance/logbook.controller.acceptance.ts
sci-log-db/src/__tests__/acceptance/paragraph.controller.acceptance.ts
sci-log-db/src/__tests__/acceptance/task.controller.acceptance.ts
sci-log-db/src/controllers/logbook.controller.ts
sci-log-db/src/controllers/task.controller.ts
sci-log-db/src/mixins/basesnippet.repository-mixin.ts

Add new snippet type not to mix snippets

---

sci-log-db/src/__tests__/acceptance/authentication.acceptance.ts
sci-log-db/src/repositories/autoadd.repository.base.ts
sci-log-db/src/services/ldap-user-service.ts
sci-log-db/src/services/user-service.ts

Concat email address to list of roles to all

---

scilog/src/app/core/remote-data.service.ts

added deleted=false to logbookitemdata query to remove deleted snippets

FIX: added deleted=false to logbookitemdata query; closes #107

---

sci-log-db/src/__tests__/unit/authentication-strategies.oidc.unit.ts
sci-log-db/src/authentication-strategies/types.ts

Fix firstName and lastName generation from profile

---

scilog/src/app/logbook/core/snippet/snippet-content/snippet-content.component.ts

Open images in new tab

---

sdk/python/scilog/scilog.py
sdk/python/tests/test_scilog.py

More details here: https://stackoverflow.com/questions/74308059/using-typeguard-decorator-typechecked-in-python-whilst-evading-circular-impor

Fix typeerror lazy loading problem

---

scilog/src/app/logbook/core/snippet/snippet.component.html
scilog/src/app/logbook/core/snippet/snippet.component.ts
scilog/src/app/logbook/widgets/logbook-item/logbook-item.component.html
scilog/src/app/logbook/widgets/logbook-item/logbook-item.component.spec.ts
scilog/src/app/logbook/widgets/logbook-item/logbook-item.component.ts

Add logic to show indexes desc when date desc

---

scilog/src/app/core/remote-data.service.ts
scilog/src/app/logbook/core/search-window/search-window.component.html
scilog/src/app/logbook/core/search-window/search-window.component.ts

Add search on subsnippets in fe

---

scilog/src/app/logbook/core/snippet/snippet.component.html
scilog/src/app/logbook/core/snippet/snippet.component.spec.ts
scilog/src/app/logbook/core/snippet/snippet.component.ts

fixed a bug when replying to a comment

Comment reply fix; closes #37

---

scilog/src/app/login/login.component.html

tabbed login to better hide the admin login if a kc connection exists
Please let me know what you think.

feat: tabbed login 

---

sdk/python/scilog/scilog.py

this is needed, otherwise https://github.com/paulscherrerinstitute/scilog/blob/main/importTools/update_locations.py#L141 and https://github.com/paulscherrerinstitute/scilog/blob/main/importTools/update_locations.py#L28 break, making the proposal sync stop

Add post_snippet method to scilog from scilogcore

---

scilog/src/app/logbook/core/add-content/add-content.component.spec.ts
scilog/src/app/logbook/core/add-content/add-content.component.ts
scilog/src/app/logbook/widgets/logbook-item/logbook-item.component.ts

I hope this fixes #129 
Please have a look. If we agree that this resolves the issue, we should add tests before merging it.

fix: fixed image update

---

scilog/src/app/logbook/core/add-content/add-content.component.spec.ts
scilog/src/app/logbook/core/add-content/add-content.component.ts

fixed a bug that caused the editor to ignore any previously set styles

fix: fixed editor style for resized images

---

scilog/src/app/logbook/core/snippet/snippet-content/snippet-content.component.spec.ts
scilog/src/app/logbook/core/snippet/snippet-content/snippet-content.component.ts

cleaned up snippet-content and removed deprecated blob handling

refactor: cleaned up snippet-content 

---

scilog/src/app/logbook/dashboard/dashboard-item/export-dialog/export-dialog.component.css
scilog/src/app/logbook/dashboard/dashboard-item/export-dialog/export-dialog.component.html
scilog/src/app/logbook/dashboard/dashboard-item/export-dialog/export-dialog.component.spec.ts
scilog/src/app/logbook/dashboard/dashboard-item/export-dialog/export-dialog.component.ts

Disable export to zip folder

---

docker-compose.dev.yaml
sci-log-db/Dockerfile
sci-log-db/package-lock.json
sci-log-db/package.json
sci-log-db/src/__tests__/acceptance/basesnippet.controller.acceptance.ts
sci-log-db/src/__tests__/unit/service.export-snippet.unit.ts
sci-log-db/src/index.ts
sci-log-db/src/mixins/basesnippet.repository-mixin.ts
sci-log-db/src/models/location.model.ts
sci-log-db/src/models/paragraph.model.ts
sci-log-db/src/services/export-snippets.service.ts
sci-log-db/src/services/pdf.css

Draft PR to collect feedbacks. 
Tests are missing and style might be improved

Pdf refactor

---

scilog/src/app/core/remote-data.service.spec.ts
scilog/src/app/core/remote-data.service.ts
scilog/src/app/logbook/widgets/widget-preferences/widget-preferences.component.html
scilog/src/app/logbook/widgets/widget-preferences/widget-preferences.component.spec.ts
scilog/src/app/logbook/widgets/widget-preferences/widget-preferences.component.ts

- target logbook mandatory
- lighter target and additional logbooks selection to overcome delayed load
- heavy load in afterViewInit

Make target logbook mandatory editing widget

---

scilog/src/app/core/toolbar/toolbar.component.html
scilog/src/app/core/toolbar/toolbar.component.scss
scilog/src/app/core/toolbar/toolbar.component.ts

Add username below avatar image

---

scilog/src/app/logbook/core/snippet/snippet-content/snippet-content.component.css
scilog/src/app/logbook/core/snippet/snippet-content/snippet-content.component.spec.ts
scilog/src/app/logbook/core/snippet/snippet-content/snippet-content.component.ts

Fix new line displaying when using enter

---

sci-log-db/src/__tests__/acceptance/basesnippet.controller.acceptance.ts
sci-log-db/src/mixins/basesnippet.repository-mixin.ts
sci-log-db/src/repositories/autoadd.repository.base.ts

a user is asking to share logbooks with PhD students and this currently encounters the limitation of not being able after expiration. I think the expiration does not make sense in this case, as she is only willing to modify the logbook to share, so this rule is relaxed here.
This PR allows an admin to change the readACL (only) of the logbook even after expiration.
The question is now if an admin should bypass the expiration in all cases, not only when setting the readACL, or if anyone should be able to share

Allow adding users to readACL after expiration

---

sdk/python/scilog/scilog.py

this is used [here](https://github.com/paulscherrerinstitute/scilog/blob/main/importTools/update_locations.py#L105) and breaks otherwise

Add post_location function to scilog

---

scilog/src/app/app.component.spec.ts
scilog/src/app/app.component.ts

Unset logbook id when clicking browser back button

---

scilog/src/app/core/model/logbooks.ts
scilog/src/app/core/remote-data.service.ts
scilog/src/app/overview/add-logbook/add-logbook.component.html
scilog/src/app/overview/add-logbook/add-logbook.component.spec.ts
scilog/src/app/overview/add-logbook/add-logbook.component.ts
scilog/src/app/overview/logbook-cover/logbook-cover.component.html
scilog/src/app/overview/logbook-cover/logbook-cover.component.spec.ts
scilog/src/app/overview/logbook-cover/logbook-cover.component.ts

Enable the sharing of logbooks, including form checks and invalidation 

---

sci-log-db/src/__tests__/acceptance/logbook.controller.acceptance.ts
sci-log-db/src/mixins/basesnippet.repository-mixin.ts
sci-log-db/src/models/logbook.model.ts

justified by plan to change the thumbnail of logbook to the file hash rather than the id

Partial revert PR: #324

---

scilog/src/app/core/model/logbooks.ts
scilog/src/app/overview/logbook-cover/logbook-cover.component.spec.ts
scilog/src/app/overview/logbook-cover/logbook-cover.component.ts

justified by plan to change the thumbnail of logbook to the file hash rather than the id

Partially revert PR #323

---

scilog/src/app/logbook/widgets/logbook-item/logbook-item.component.html
scilog/src/app/logbook/widgets/logbook-item/logbook-item.component.scss
scilog/src/app/logbook/widgets/logbook-item/logbook-item.component.spec.ts
scilog/src/app/logbook/widgets/logbook-item/logbook-item.component.ts

Add scroll to bottom button and tests

---

sci-log-db/src/__tests__/unit/service.export-snippet.unit.ts
sci-log-db/src/services/export-snippets.service.ts
sci-log-db/src/services/pdf.css

Add new line when table is rotated into landscape

---

sci-log-db/package-lock.json
sci-log-db/package.json
sci-log-db/src/__tests__/acceptance/basesnippet.controller.acceptance.ts
sci-log-db/src/__tests__/unit/service.export-snippet.unit.ts
sci-log-db/src/mixins/basesnippet.repository-mixin.ts
sci-log-db/src/services/export-snippets.service.ts
sci-log-db/src/services/pdf.css

Compress in gz folder when attachments in export

---

sci-log-db/fixtures/users/00.yml
sci-log-db/fixtures/users/01.yml
sci-log-db/fixtures/users/02.yml
sci-log-db/fixtures/users/03.yml
sci-log-db/src/__tests__/acceptance/migrate.acceptance.ts
sci-log-db/src/__tests__/acceptance/paragraph.controller.acceptance.ts
sci-log-db/src/__tests__/unit/utils.misc.unit.ts
sci-log-db/src/application.ts
sci-log-db/src/models/paragraph.model.ts
sci-log-db/src/repositories/autoadd.repository.base.ts
sci-log-db/src/repositories/paragraph.repository.ts
sci-log-db/src/utils/misc.ts

Build extra field for paragraphs which allows to index text of HTML without tags or special chars

Html textcontent index

---

sci-log-db/src/__tests__/acceptance/basesnippet.controller.acceptance.ts
sci-log-db/src/__tests__/acceptance/task.controller.acceptance.ts
sci-log-db/src/controllers/task.controller.ts
sci-log-db/src/mixins/basesnippet.repository-mixin.ts

Make expiration check on update optional

---

scilog/src/app/logbook/core/search-window/search-window.component.spec.ts
scilog/src/app/logbook/core/search-window/search-window.component.ts
scilog/src/app/logbook/core/search/search.component.spec.ts
scilog/src/app/logbook/core/search/search.component.ts
scilog/src/app/logbook/widgets/logbook-item/logbook-item.component.spec.ts
scilog/src/app/logbook/widgets/logbook-item/logbook-item.component.ts

Pass config to search
